### ISSUE TITLE
Gegnerisches Team wird vor Beginn der Ballanimation zurückgesetzt

### ISSUE THREAD

**Issue by kinnla** [Hot-Ball-Gruppe/Hot-Ball#11]
PRECONDITION: Gegnerisches Team wirft auf den Korb.
ACTION: --
OBSERVED BEHAVIOR: Das gegnerische Team wird neu aufgebaut und die Ballanimation wird gezeigt.
EXPECTED BEHAVIOR: Die Ballanimation wird gezeigt, und erst nach deren Ende (und wenn der Ball rein geht) wird das gegnerische Team zurückgesetzt.

Man kann also vor Ende der Animation wissen, ob der Ball rein geht oder nicht.

**Comment by addymi** [comment]
Ist bekannt, Überlegung ist momentan ob das beibehalten werden soll oder nicht

**Comment by addymi** [comment]
werden nun zurückgesetzt, erst nachdem die Korb-Animation zurückgesetzt ist.
FIXED
