### ISSUE TITLE
KI-Ballcarrier trifft den Korb über Bande nicht

### ISSUE THREAD

**Issue by gottfried-bammes** [Hot-Ball-Gruppe/Hot-Ball#13]
1) Starte Spiel mit nur einem Spieler in jedem Team
2) Gebe der KI den Ball und positioniere dich vor dem Korb
3) Die KI versucht, über Bande auf den Korb zu werfen, und sollte treffen
4) Stattdessen verfehlt sie in den meisten Fällen um Haaresbreite

**Comment by addymi** [comment]
FIXED
