### ISSUE TITLE
Spiel startet nicht

### ISSUE THREAD

**Issue by kinnla** [Hot-Ball-Gruppe/Hot-Ball#4]
PRECONDITION: OSX, auf der Konsole im Verzeichnis `HotballGDX`
ACTION: `./gradlew desktop:run`
OBSERVED BEHAVIOR: Spiel startet nicht (Fehler, stacktrace siehe unten)
EXPECTED BEHAVIOR: Das Spiel startet

> Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
>     at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:131)
> Caused by: java.lang.ExceptionInInitializerError
>     at com.hot.ball.hotball.universe.player.Player.<init>(Player.java:98)
>     at com.hot.ball.hotball.universe.player.Player.<clinit>(Player.java:34)
>     at com.hot.ball.HotballGame.create(HotballGame.java:32)
>     at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
>     at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
> Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: res/Tackle0.png
>     at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:148)
>     at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
>     at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
>     at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
>     at com.hot.ball.hotball.universe.zone.TackleZone.<clinit>(TackleZone.java:73)
>     ... 5 more
> Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: res/Tackle0.png (Internal)
>     at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
>     at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
>     at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:145)
>     ... 9 more

**Comment by Dromlius** [comment]
Dies ist ein bekanntest Problem auf non-Windows Systemen.
Der einfache Fix ist in Zeile 73 der Kasse `com.hot.ball.hotball.universe.zone.TackleZone`:
`TEXTURE[i] = new TextureRegion(new Texture(Gdx.files.internal("res/`**T**`ackle" + i + ".png")));`
in
`TEXTURE[i] = new TextureRegion(new Texture(Gdx.files.internal("res/`**t**`ackle" + i + ".png")));`
zu ändern.
Bei Zeiten werden wir uns darum kümmern dies permanent zu beheben.

**Comment by kinnla** [comment]
danke für den Hinweis! Bitte noch im Sourcecode fixen.
