### ISSUE TITLE
Ice-Level nicht unterstützt

### ISSUE THREAD

**Issue by Dromlius** [Hot-Ball-Gruppe/Hot-Ball#5]
PRECONDITION: Projekt in Entwicklungsumgebung geladen und das Ice-Level gewählt
ACTION: als Desktop-Applikation ausführen
OBSERVED BEHAVIOUR: das Programm stürzt ab bei dem Versuch die Textur zu laden, obwohl sie vorhanden ist.
EXPECTED BEHAVIOUR: das Programm lädt die vorhandene Textur.

**Comment by addymi** [comment]
Ice-Level removed
