### ISSUE TITLE
Keinerlei Spielmenü vorhanden

### ISSUE THREAD

**Issue by repthor** [Hot-Ball-Gruppe/Hot-Ball#6]
PRECONDITION: Projekt in Entwicklungsumgebung geladen
ACTION: als Desktop-Applikation ausführen
OBSERVED BEHAVIOUR: das Programm beginnt unvermittelt mit schmissiger Musik in einer Spielsituation
EXPECTED BEHAVIOUR: das Programm beginnt mit einem Menü

**Comment by repthor** [comment]
Verantwortlich: Repmann
Bearbeitungsstand: Game- und (noch leerer) Menü-Screen, sowie Umschaltlogik implementiert (nur im lokalen repository: Maserstand: gestern nachmittag; "repthor-Testcommit") 
Bemerkung: Ich setze den Arbeitstag zunächst in Heimarbeit fort. 
                    Bin online, erbitte Wünsche zwecks Menü-Inhalt, 
                    Ich denke, das sollte via Git so funktionieren, dass ich den dann aktuellen Master-
                    Branch-Stand pulle und lokal merge? Wenn das läuft, würde ich dann die gemergte
                    Variante pushen. Falls dieser Plan schlecht: bitte Info!
Schönen Arbeitstag!

**Comment by repthor** [comment]
das "daß" ist ein "das"

**Comment by repthor** [comment]
Moin Felix,

Du warst ja fleissig heute nacht! Resekt!
Habe den Menüstand, den ich Dir gestern auf Stick gegeben hatte, eben um die Schaltflächen "nach oben", unten, links und rechts ergänzt und die Bildchen dazu gebaut und einige Schaltflächen um Texte ergänzt.
Habe dann versucht, das ganze mit Deinem Commit von heute morgen zu mergen. In den drei Screen-Files ging das, aber es kamen viele andere Fehler (sieht aus, als hätte sich die JRE-umgebung geändert oder so).
Ich denke jedenfalls, wenn ich hier irgendwas pushte, würde dies sehr wahrscheinlich Murks. Gangbarer erscheint wir der Weg, wenn ich Dir die 3 Quelltexte und die neuen Bilder mailte und Du sie einfach in Dein Projekt kopiertest und dann selber comittetest.
Melde Dich, wenn Du es brauchst und wohin ich es schicken soll! Ansonsen dann eben bis nachher!

**Comment by addymi** [comment]
Spielmenü vorhanden!
FIXED
